version: "3"
services:
  dst-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: dst-bot:${IMAGE_TAG:-latest}
    restart: always
    environment:
      - ACCOUNT=${ACCOUNT:-机器人QQ号}
      - KLEI_TOKEN=${KLEI_TOKEN:-科雷令牌}
      - WENDY_API=${WENDY_API:-}
      - NAPCAT_API=http://napcat:3000
      - DATABASE_URL=sqlite:/app/data/bot.sqlite3
    volumes:
      - ${PWD}/data/dst-bot:/app/data
      - ${PWD}/data/napcat/QQ:/app/.config/QQ
    ports:
      - "${PORT:-8000}:8000"
  napcat:
    image: mlikiowa/napcat-docker:latest
    restart: always
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    volumes:
      - ${PWD}/data/napcat/QQ:/app/.config/QQ
      - ${PWD}/data/napcat/config:/app/napcat/config
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6099:6099"
